#+TITLE: Ejemplo de Literate Programming: Javascript
#+AUTHOR: Martín Alsinet
#+DATE: 2017
#+OPTIONS: ':t num:nil
#+LANGUAGE: es

* Introducción

  En este documento vamos a explorar las técnicas de Literate Programming con un ejemplo práctico en Javascript.

  El objetivo del ejemplo es analizar un archivo de estadísticas de accidentes en la ciudad de Medellín y armar una página sencilla con los resultados más interesantes.

** Disclaimer

Este es un ejercicio a modo de ejemplo y el código no representa en absoluto las mejores prácticas respecto de seguridad o control de errores. 

Más claro: *No copiar y pegar fragmentos de este código en una aplicación productiva.* (para eso está StackOverflow)

* Mini-Tutorial de Org-mode
** Titulo, autor y opciones

- text-mode | org-mode

** Navegación, TODOs y checkboxes

- tab | shift-tab
- TODOs
- checkboxes

- [ ] item 1
  - [ ] subitem 1.1
  - [ ] subitem 1.2
  - [ ] subitem 1.3

** Bloques de código
*** Lenguajes

- shell :: ifconfig | grep inet
- javascript :: process.versions
- python :: sys.version

*** Features

- tangle
- results: output|table|raw
- drawer
- session

* Setup
** Inicializar carpetas

Vamos a guardar el código fuente de la aplicación en la carpeta =src=. Debido a que utilizamos =org-babel-tangle= para generar los archivos .js a partir de este documento, no es necesario que la carpeta sea registrada en el repositorio.

Para comenzar desde cero borramos las carpetas =node_modules=, =src=, y el archivo que vamos a usar como base de datos (=database.db=).

#+BEGIN_SRC sh :results output drawer
#rm -Rf ./node_modules ./src ./database.db
#mkdir -p src
#ls -l
#cat .gitignore
#+END_SRC

** Generar package.json

Generamos un =package.json= mínimo para comenzar el proyecto

#+BEGIN_SRC js :tangle package.json
{
  "name": "literate-programming-example",
  "version": "0.1.0",
  "description": "Ejemplo de Literate Programming en Javascript",
  "main": "src/server.js",
  "scripts": {
      "start": "node src/server.js"
  },
  "author": "Martín Alsinet",
  "license": "CC"
}
#+END_SRC

** Instalar dependencias

Vamos a necesitar las siguientes dependencias

- sqlite :: Base de datos en un archivo
- csv-parse  :: Parser de archivos CSV
- express :: Webserver

#+BEGIN_SRC sh :results output drawer
npm install sqlite3 csv-parse express
#+END_SRC

* Fuente de datos
** Origen

La fuente de los datos que vamos a usar es la iniciativa de Open Data de la Alcaldía de Medellín, que pone a disposición [[https://geomedellin-m-medellin.opendata.arcgis.com/datasets/a65c3aff0ef34973a2441b6cd0fbc24a_8][las estadísticas de accidentes de tránsito del año 2016]]

** Formato

El formato de los datos es un archivo CSV, veamos qué tiene adentro

#+BEGIN_SRC sh
head -n 3 Accidentalidad_2016.csv
#+END_SRC

** ¿Qué columnas me interesan?

Seleccioné las siguientes columnas para extraer del archivo:

- objectid
- fecha
- hora
- dia
- clase
- gravedad
- barrio
- comuna
- diseño

La fecha y la hora están en dos campos separados, vamos a fusionarlas en uno solo.

Aparentemente hay una ubicación geográfica, porque están los campos =X= e =Y=, pero no son campos de latitud y longitud sino que la ubicación está en formato ARCGIS. Para no complicar el ejemplo, no vamos a utilizar las coordenadas.

* Importar CSV a una base sqlite
** Parsear CSV

   Para parsear el archivo usamos el módulo =csv-parse= que permite leer un archivo y pasarle una función que recibe un array de objetos con un registro por cada fila.

   Entre las opciones disponibles, utilizo el parámetro =columns= para pasarle una función que recibe la primera fila (los encabezados) y debe devolver un array con los nombres de cada columna. Además uso el parámetro =trim: true= para que el módulo csv le quite a los registros automáticamente los espacios en blanco que haya a ambos lados del contenido de cada celda. La otra opción que uso es =ops.to= que permite cortar el procesamiento del archivo luego de un número de líneas.

#+BEGIN_SRC js :results output drawer :tangle src/parser.js
const fs = require('fs');
const parse = require('csv-parse')


function columns(line)
{
    return line.map(s => s.toLowerCase());
}


parse_csv = function(filename, fn, limit){
    fs.readFile(filename, "utf8", function (err, fileData) {
        var opts = {columns: columns, trim: true};
        if (limit) {
            opts.to = limit;
        }
        parse(fileData, opts, (err, rows) => fn(rows));
    });
}

module.exports = parse_csv;

//parse_csv('Accidentalidad_2016.csv', console.log, 2);
#+END_SRC

** Crear Schema

Ahora creo un objeto =schema= que me permite realizar algunas operaciones de mantenimiento de la base de datos. Uso estas operaciones para verificar el funcionamiento del proceso de inserción.

Los métodos del objeto =schema= son:

- create :: Crea la tabla =accidentes= ejecutando la query =schema_q=
- truncate :: Borra todos los registros de la tabla =accidentes=
- rows :: Ejecuta un =SELECT= de la tabla =accidentes= e imprime todos los registros de la tabla con =console.log=
- count :: Ejecuta un =SELECT count(1)= de la tabla =accidentes= e imprime el resultado con =console.log=

#+BEGIN_SRC js :results output drawer :tangle src/schema.js
var schema_q = `CREATE TABLE IF NOT EXISTS accidentes (
      id INTEGER PRIMARY_KEY,
   fecha TEXT,
     dia TEXT,
   clase TEXT,
gravedad TEXT,
  barrio TEXT,
  comuna TEXT,
  diseno TEXT
)`


var schema = function(db) {
    return {
        create: function(){
            db.serialize(function() {
                db.run("DROP TABLE IF EXISTS accidentes");
                db.run(schema_q);
            });
        },
        truncate: function(){
            db.serialize(function() {
                db.run("BEGIN TRANSACTION");
                db.run("DELETE FROM accidentes");
                db.run("COMMIT");
            });
        },
        rows: function(limit){
            db.all(
                "SELECT * FROM accidentes LIMIT " + limit, 
                (err, records) => console.log(records)
            );
        },
        count: function(){
            db.all(
                "SELECT COUNT(1) AS rows FROM accidentes", 
                (err, records) => console.log(records)
            );
        }
    };
};

module.exports = schema;

//const sqlite3 = require('sqlite3').verbose();
//var s = schema(new sqlite3.Database('database.db'));
//s.create();
//s.rows(3);
//s.count();
#+END_SRC

** Insertar registros

Para insertar los datos parseados uso la función =insert= definida más abajo que ejecuta la query =insert_q= para cada fila del archivo original. Los inserts se ejecutan dentro de una transacción en un entorno serializado, lo que asegura los datos se inserten en secuencia. Luego del commit de la tranasacción se llama a una función =finished= que indica que se ha terminado de procesar los datos.

Antes de insertar cada registro uso la función =fix_date= que fusiona los dos campos =fecha= y =hora= en un solo campo =fecha= con toda la información. Además le cambia el formato a la hora, dado que en el archivo original se encuentra en formato AM/PM y eso complica las consultas.

Las funciones show_X las uso solamente para poder mostrar cómo se van modificando los datos, desde el parseo original, pasando por las correcciones de la fecha y luego la query resultante que se va a ejecutar.

#+BEGIN_SRC js :results output drawer
var insert_q = `INSERT INTO accidentes (
  id, fecha, dia, clase, gravedad, 
  barrio, comuna, diseno
) VALUES (
  :objectid, ':fecha', ':dia', ':clase', ':gravedad', 
  ':barrio', ':comuna', ':diseno'
)
`;


function query(q, val) {
    return q
        .replace(':objectid', val.objectid)
        .replace(':fecha', val.fecha)
        .replace(':dia', val.dia)
        .replace(':clase', val.clase)
        .replace(':gravedad', val.gravedad)
        .replace(':barrio', val.barrio)
        .replace(':comuna', val.comuna)
        .replace(':diseno', val.diseno)
}


function ampm_to_24h(text)
{
    var hour = parseInt(text.substr(0,2));
    var ampm = text.substr(6,2);
    if ((hour == 12) && (ampm == "AM")) {
        hour = 0;
    }
    if ((hour != 12) && (ampm == "PM")) {
        hour+= 12;
    }
    return ("0"+String(hour)).substr(-2)+":"+text.substr(3,2);
}


function fix_date(row)
{
    row.fecha = row.fecha.substr(0,10) + " " + ampm_to_24h(row.hora);
    return row;
}


function show_r(rows)
{
    rows.map(function(row){
        console.log(row);
        console.log("");
    });
}


function show_f(rows)
{
    rows.map(function(row){
        console.log(fix_date(row));
        console.log("");
    });
}


function show_q(rows)
{
    rows.map(function(row){
        console.log(query(insert_q, fix_date(row)));
    });
}


function show(rows)
{
    rows.map(function(row){
        console.log(row);
        console.log("");
        console.log(query(insert_q, row));
        console.log(query(insert_q, fix_date(row)));
    });
}


function finished()
{
    if (schema !== null) {
        schema.count();
        //schema.rows();
    }
}


function insert(rows)
{
    db.serialize(function() {
        db.run("begin transaction");
        rows.map(function(row){
            db.run(query(insert_q, fix_date(row)));
        });
        db.run("commit");
        finished();
    });
}


const sqlite3 = require('sqlite3').verbose();
const parser = require("/app/src/parser.js");
const db_schema = require("/app/src/schema.js");
const inputFile = 'Accidentalidad_2016.csv';
var db = new sqlite3.Database('database.db');

// Ejemplos:
//parse_csv(inputFile, show_r, 2);
//parse_csv(inputFile, show_f, 2);
//parse_csv(inputFile, show_q, 2);
//parse_csv(inputFile, show, 2);

//schema = db_schema(db);
//schema.truncate();
//parse_csv(inputFile, insert, 5);
//parse_csv(inputFile, insert);
//schema.count();
#+END_SRC

* Explorar algunas consultas interesantes

Me gustaría obtener la siguiente información:

- Cantidad de accidentes por mes
- Cantidad de accidentes por día de la semana
- Cantidad de accidentes por hora del día
- Cantidad de accidentes por gravedad
- Cantidad de accidentes por comuna y barrio
- Cantidad de accidentes por lugar

** Queries

En esta sección creo el objeto =query= que almacena cada una de las consultas que voy a utilizar. Además le agregué un método =rows= que devuelve un select de la tabla para cuando quiera revisar los registros individualmente.

#+BEGIN_SRC js :results output raw drawer :tangle src/queries.js
var query = {
    rows: function(limit){
        return "SELECT * FROM accidentes LIMIT " + limit;
    },

    por_mes: 
` SELECT substr(fecha, 0, 8) AS mes, count(1) AS accidentes 
    FROM accidentes 
GROUP BY substr(fecha, 0, 8)
ORDER BY 1`,

    por_dia: 
` SELECT dia, count(1) AS accidentes 
    FROM accidentes 
GROUP BY dia
ORDER BY 2`,

    por_hora: 
` SELECT substr(fecha, 12, 2) as hora, count(1) AS accidentes 
    FROM accidentes 
GROUP BY substr(fecha, 12, 2)
ORDER BY 1`,

    por_gravedad: 
` SELECT gravedad, count(1) AS accidentes 
    FROM accidentes 
GROUP BY gravedad
ORDER BY 2 DESC`,

    por_comuna: 
` SELECT comuna, count(1) AS accidentes 
    FROM accidentes 
GROUP BY comuna
ORDER BY 2 DESC`,

    por_barrio: 
` SELECT barrio, count(1) AS accidentes 
    FROM accidentes 
GROUP BY barrio
ORDER BY 2 DESC`,

    por_comuna_y_barrio: 
` SELECT comuna, barrio, count(1) AS accidentes 
    FROM accidentes 
GROUP BY comuna, comuna, barrio
ORDER BY 3 DESC`,

    por_diseno:
` SELECT diseno, count(1) AS accidentes 
    FROM accidentes 
GROUP BY diseno
ORDER BY 2 DESC`
};

module.exports = query;

//  const table = require('/app/src/table.js');
//  const sqlite3 = require('sqlite3').verbose();
//  var db = new sqlite3.Database('database.db');
//  db.all(
//         query.por_dia, 
// //        (err, rows) => console.log(rows)
//         (err, rows) => table(rows)
//  );
#+END_SRC



#+NAME: q-dia
#+BEGIN_SRC sqlite :db database.db :results table drawer
select dia, count(1) as accidentes
from accidentes
group by dia
order by 2 desc;
#+END_SRC

** Modelo

En esta sección, usando el objeto =query=, creo un objeto =accidentes= que es el que se encarga de realizar efectivamente las consultas sobre la base de datos. Debido a que es un ejercicio de ejemplo no le agregué ningún tipo de control de errores. Si la query falla por algún motivo node va a devolver el error en la consola.

#+BEGIN_SRC js :results output raw drawer :tangle src/accidentes.js
var accidentes = function(db, query){
    return {
        rows: function(limit, fn){
            db.all(
                query.rows(limit), 
                (err, rows) => fn(rows)
            );
        },
        por_mes: function(fn){
            db.all(
                query.por_mes, 
                (err, rows) => fn(rows)
            );
        },
        por_dia: function(fn){
            db.all(
                query.por_dia, 
                (err, rows) => fn(rows)
            );
        },
        por_hora: function(fn){
            db.all(
                query.por_hora, 
                (err, rows) => fn(rows)
            );
        },
        por_gravedad: function(fn){
            db.all(
                query.por_gravedad, 
                (err, rows) => fn(rows)
            );
        },
        por_barrio: function(fn){
            db.all(
                query.por_barrio, 
                (err, rows) => fn(rows)
            );
        },
        por_comuna: function(fn){
            db.all(
                query.por_comuna, 
                (err, rows) => fn(rows)
            );
        },
        por_comuna_y_barrio: function(fn){
            db.all(
                query.por_comuna_y_barrio, 
                (err, rows) => fn(rows)
            );
        },
        por_diseno: function(fn){
            db.all(
                query.por_diseno, 
                (err, rows) => fn(rows)
            );
        },
    };
}

const query = require('/app/src/queries.js');
const sqlite3 = require('sqlite3').verbose();

var db = new sqlite3.Database('database.db');
var acc = accidentes(db, query);

module.exports = acc;

//acc.por_comuna(console.log);
//acc.rows(4, console.log);
#+END_SRC

*** Ver como tabla

#+BEGIN_SRC js :tangle src/table.js
function table_row(cells){
    console.log("|" + cells.join("|") + "|");
}


function table(rows){
    console.log("|---|");
    table_row(Object.keys(rows[0]));
    console.log("|---|");
    rows.map(row => table_row(Object.keys(row).map(k => row[k])));
    console.log("|---|");
}

module.exports = table;
#+END_SRC

* Exponer las consultas en una API JSON

Para crear la API me baso en el objeto accidentes del punto anterior.

#+BEGIN_SRC js :results output raw drawer
var accidentes = require("/app/src/accidentes.js");
var view_as_table = require("/app/src/table.js");

//accidentes.por_dia(console.log);
#+END_SRC

** Controlador

Creo un controlador que agrega métodos para exponer las consultas.

#+BEGIN_SRC js :tangle src/controller.js
var accidentes = require('/app/src/accidentes.js');

exports.por_mes = function(req, res){
    accidentes.por_mes(rows => res.json(rows));
}

exports.por_dia = function(req, res){
    accidentes.por_dia(rows => res.json(rows));
}

exports.por_hora = function(req, res){
    accidentes.por_hora(rows => res.json(rows));
}

exports.por_gravedad = function(req, res){
    accidentes.por_gravedad(rows => res.json(rows));
}

exports.por_comuna = function(req, res){
    accidentes.por_comuna(rows => res.json(rows));
}

exports.por_barrio = function(req, res){
    accidentes.por_barrio(rows => res.json(rows));
}

exports.por_comuna_y_barrio = function(req, res){
    accidentes.por_comuna_y_barrio(rows => res.json(rows));
}

exports.por_diseno = function(req, res){
    accidentes.por_diseno(rows => res.json(rows));
}
#+END_SRC

** Rutas

#+BEGIN_SRC js :tangle src/routes.js
module.exports = function(app) {
  var accidentes = require('/app/src/controller.js');

  app.route('/accidentes/por_mes')
    .get(accidentes.por_mes);

  app.route('/accidentes/por_dia')
    .get(accidentes.por_dia);

  app.route('/accidentes/por_hora')
    .get(accidentes.por_hora);

  app.route('/accidentes/por_gravedad')
    .get(accidentes.por_gravedad);

  app.route('/accidentes/por_comuna')
    .get(accidentes.por_comuna);

  app.route('/accidentes/por_barrio')
    .get(accidentes.por_barrio);

  app.route('/accidentes/por_comuna_y_barrio')
    .get(accidentes.por_comuna_y_barrio);

  app.route('/accidentes/por_diseno')
    .get(accidentes.por_diseno);

};
#+END_SRC

** Servidor

En esta sección creamos el servidor que va a ser responsable por la API REST y la página que muestra las estadísticas. Va a escuchar en el puerto *3000* y lo iniciamos con el comando =node src/server.js=, o sino con =npm start=.

#+BEGIN_SRC js :tangle src/server.js
var express = require('express');
var app = express();
var port = process.env.PORT || 3000;
var routes = require('/app/src/routes.js');
routes(app);

app.get('/', function(req, res) {
    res.sendFile('/app/src/index.html');
});

app.use(function(req, res) {
  res.status(404).send({url: req.originalUrl + ' not found'})
});

app.listen(port, '0.0.0.0');

// exit with ctrl-c when started standalone
process.on('SIGINT', function() {
    console.log(": Caught interrupt signal, exiting...");
    process.exit();
});

console.log('Web server started on: ' + port);
#+END_SRC

** HTTP test

Para verificar el funcionamiento de la API primero hay que ejecutar en una consola el comando =node src/server.js=, que lanza el servidor e inicia la aplicación.

Luego visitar con un navegador el siguiente url:

-  [[http://localhost:3000/accidentes/por_dia]]

O sino, ejecutar el siguiente bloque de código con =C-c C-c=

#+BEGIN_SRC sh :results output raw drawer
curl http://localhost:3000/accidentes/por_dia
#+END_SRC

* Hacer una página mínima con resultados

  La página muestra las estadísticas en forma gráfica, consultando la API JSON.

  Utilizo las siguientes bibliotecas:

- [[https://purecss.io][Pure CSS]] :: Para los estilos y layout
- [[http://jquery.com][jQuery]] :: Para hacer las peticiones AJAX
- [[http://chartjs.org][Chart.js]] :: Para generar los gráficos

Abrimos un navegador en [[http://localhost:3000/]]

** index.html

#+BEGIN_SRC html :tangle src/index.html
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8"/>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <title>Accidentes en Medellín - Año 2016</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css"/>
  </head>
  <body>
    <h1>Accidentes en Medellín - Año 2016</h1>
    <div class="pure-g">
      <div class="pure-u-1-3">
        <div class="chart">
          <canvas id="chart-por-mes" width="400" height="400">
          </canvas>
        </div>

        <div class="chart">
          <canvas id="chart-por-dia" width="400" height="400">
          </canvas>
        </div>
      </div>

      <div class="pure-u-1-3">
        <div class="chart">
          <canvas id="chart-por-hora" width="400" height="400">
          </canvas>
        </div>

        <div class="chart">
          <canvas id="chart-por-gravedad" width="400" height="400">
          </canvas>
        </div>
      </div>

      <div class="pure-u-1-3">
        <div class="chart">
          <canvas id="chart-por-comuna" width="400" height="400">
          </canvas>
        </div>

        <div class="chart">
          <canvas id="chart-por-lugar" width="400" height="400">
          </canvas>
        </div>
      </div>
    </div>

    <style>
     h1 {
       text-align: center;
     }
     div.chart {
       border: 1px solid;
       padding: 1em;
     }
    </style>

    <script>
     function random_color()
     {
         return color = [
             Math.round(Math.random()*256),
             Math.round(Math.random()*256),
             Math.round(Math.random()*256)
         ];
     }

     function rgba(rgb, alpha){
         return "rgba(" + rgb.join(", ") + ", " + alpha + ")";
     }

     function makeChart(type, title, selector, labels, records){
         var colors = records.map(x => random_color());
         var chart = new Chart(selector, {
             type: type,
             data: {
                 labels: labels,
                 datasets: [{
                     label: title,
                     data: records,
                     backgroundColor: colors.map(col => rgba(col, 0.5)),
                     borderColor: colors.map(col => rgba(col, 1)),
                     borderWidth: 1
                 }]
             },
             options: {}
         });
     }

     $(document).ready(function(){

         $.get("/accidentes/por_mes", function(data){
             labels = data.map(row => row.mes);
             records = data.map(row => row.accidentes);
             makeChart(
                 "bar", "Accidentes por Mes", "chart-por-mes", labels, records
             );
         });

         $.get("/accidentes/por_dia", function(data){
             labels = data.map(row => row.dia);
             records = data.map(row => row.accidentes);
             makeChart(
                 "bar", "Accidentes por Día", "chart-por-dia", labels, records
             );
         });

         $.get("/accidentes/por_hora", function(data){
             labels = data.map(row => row.hora);
             records = data.map(row => row.accidentes);
             makeChart(
                 "bar", "Accidentes por Hora", "chart-por-hora", labels, records
             );
         });

         $.get("/accidentes/por_gravedad", function(data){
             labels = data.map(row => row.gravedad);
             records = data.map(row => row.accidentes);
             makeChart(
                 "doughnut", "Accidentes por Gravedad", "chart-por-gravedad", labels, records
             );
         });

         $.get("/accidentes/por_comuna", function(data){
             labels = data.map(row => row.comuna);
             records = data.map(row => row.accidentes);
             makeChart(
                 "doughnut", "Accidentes por Comuna", "chart-por-comuna", labels, records
             );
         });

         $.get("/accidentes/por_diseno", function(data){
             labels = data.map(row => row.diseno);
             records = data.map(row => row.accidentes);
             makeChart(
                 "doughnut", "Accidentes por Lugar", "chart-por-lugar", labels, records
             );
         });

     });
    </script>

  </body>
</html>
#+END_SRC

* La Yapa
** Exportar a HTML

#+BEGIN_SRC text
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>
#+HTML_HEAD: <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
#+HTML_HEAD: <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/readtheorg/js/readtheorg.js"></script>
#+HTML_HEAD: <style type="text/css">pre {background-color: #ddd}</style>
#+End_SRC text

** Exportar a PDF

#+BEGIN_SRC text
#+LaTeX_HEADER: \usemintedstyle{default}
#+LaTeX_HEADER: \usepackage{xcolor}
#+LaTeX_HEADER: \definecolor{bg}{rgb}{0.95,0.95,0.95}
#+END_SRC


